"""add nombre to convocatoria

Revision ID: 62420a00584e
Revises: db165a8fae4c
Create Date: 2025-05-20 07:03:23.310000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62420a00584e'
down_revision: Union[str, None] = 'db165a8fae4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('convocatorias', sa.Column('nombre', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('convocatorias', 'nombre')
    # ### end Alembic commands ###
