"""add reset_token fields to usuario

Revision ID: c68e6d905adb
Revises: 
Create Date: 2025-05-20 00:40:13.454433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c68e6d905adb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('reset_token', sa.String(), nullable=True))
    op.add_column('usuarios', sa.Column('reset_token_expires', sa.DateTime(), nullable=True))
    op.add_column('usuarios', sa.Column('fecha_creacion', sa.DateTime(), nullable=True))
    op.add_column('usuarios', sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_usuarios_nombre'), 'usuarios', ['nombre'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_nombre'), table_name='usuarios')
    op.drop_column('usuarios', 'fecha_actualizacion')
    op.drop_column('usuarios', 'fecha_creacion')
    op.drop_column('usuarios', 'reset_token_expires')
    op.drop_column('usuarios', 'reset_token')
    # ### end Alembic commands ###
