"""add estado_id to tipo_proyecto

Revision ID: db165a8fae4c
Revises: c68e6d905adb
Create Date: 2025-05-20 02:01:58.570205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db165a8fae4c'
down_revision: Union[str, None] = 'c68e6d905adb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tipos_proyecto', sa.Column('estado_id', sa.Integer(), nullable=True))
    op.alter_column('tipos_proyecto', 'nombre',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'tipos_proyecto', 'estados', ['estado_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tipos_proyecto', type_='foreignkey')
    op.alter_column('tipos_proyecto', 'nombre',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('tipos_proyecto', 'estado_id')
    # ### end Alembic commands ###
