from .usuario import Usuario
from .rol import Rol
from .estado import Estado
from .tipo_estado import TipoEstado
from .facultad import Facultad
from .extension import Extension
from .proyecto import Proyecto
from .cierre import Cierre
from .evaluacion import Evaluacion
from .destino import Destino
from .convocatoria import Convocatoria
from .conceptoevaluacion import ConceptoEvaluacion
from .cronograma import Cronograma
from .recurso import Recurso
from .participante import Participante
from .avance import Avance
from .producto import Producto
from .tarea import Tarea
from .auditoria import Auditoria
from .anexo import Anexo
from .lineainvestigacion import LineaInvestigacion
from .grupoinvestigacion import GrupoInvestigacion
from .notificacion import Notificacion
from .programa import Programa
from .impacto import Impacto
from .seguimiento import Seguimiento
from .tipo_proyecto import TipoProyecto
# Añade aquí más importaciones de modelos según sea necesario
